API_HOST = "0.0.0.0"
API_PORT = 8000

ENABLE_PATTERN_DETECTOR = True
ENABLE_STATISTICAL_DETECTOR = True
ENABLE_ML_DETECTOR = True
ENABLE_TEMPORAL_DETECTOR = True

ZSCORE_THRESHOLD = 3.0
RATE_SPIKE_RPM_THRESHOLD = 120
ERROR_RATE_THRESHOLD_PCT = 40.0

ML_CONTAMINATION = 0.05
ML_N_ESTIMATORS = 100

BUSINESS_HOURS_START = 7
BUSINESS_HOURS_END = 20

BURST_EVENT_COUNT = 20
BURST_WINDOW_SECONDS = 10

SEVERITY_CRITICAL_THRESHOLD = 80
SEVERITY_HIGH_THRESHOLD = 50
SEVERITY_MEDIUM_THRESHOLD = 25

REPORT_OUTPUT_PATH = "anomaly_report.html"
MAX_EVENTS_PER_ALERT_IN_REPORT = 5

SUPPORTED_FORMATS = ["syslog", "apache", "windows_event", "generic"]